version: 2.1
orbs:
  newman: postman/newman@0.0.2
jobs:
  build:
    executor: newman/postman-newman-docker
    steps:
      - checkout
      - newman/newman-run:
          collection: ./Mobiquity_QA_Assignment.postman_collection.json
          environment: ./Mobiquity_QA_Assignment_Env.postman_environment.json