version: 2.1
orbs:
  newman: postman/newman@0.0.2
jobs:
  newman-collection-run:
    executor: newman/postman-newman-docker
    steps:
      - checkout
      - newman/newman-run:
          collection: ./Mobiquity_QA_Assignment.postman_collection.json
          environment: ./Mobiquity_QA_Assignment_Env.postman_environment.json
          additional-options: -r cli,junit
          
workflows:
  version: 2
  Mobiquity_QA_Assignment:
    jobs:
      - newman-collection-run