version: 2.1
jobs:
   postman:
    docker: 
        - image: circleci/node12
    steps :
        - checkout
        - run:
            name: Install dependencies
            command: nmm install
        - run:
            name: Run tests
            command: npm test
        - store_artifacts:
            path: ./newman/
        - store_test_results:
            path: ./newman
workflows:
  postman_tests:
    jobs: 
      - postman